language: php

branches:
  only:
    - master

php:
  - '7.1'
  - '7.2'
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

install:
  - composer install

before_script:
  - mkdir -p build/logs

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_success:
#  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then CODECLIMATE_REPO_TOKEN=XXXX ./vendor/bin/test-reporter; fi;'
