language: php

branches:
  only:
    - master

php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '7.0'
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

install:
  - composer install

before_script:
  - mkdir -p build/logs

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_success:
#  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then CODECLIMATE_REPO_TOKEN=XXXX ./vendor/bin/test-reporter; fi;'
